server:
  port: 8081 #使用 8000 和 8001 测试多个应用
spring:
  application:
    name: products  #全部小写
  http:
      multipart:
        max-file-size: 2000Mb #上传最大文件容量
        max-request-size: 2500Mb #最大请求容量
logging: # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com:  #为包名的开始，那个包下面的以dbug打印
      zht:
        dao : debug #showSql
mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml #配置mybatis的xml扫描位置
  type-aliases-package: com.zht.bean #实体类


